version: '3.8'

services:
  charge_request:
    build: ./charge_request_service
    ports:
      - "4000:4000"
  
  load_balancer:
    build: ./load_balancer
  
  substation1:
    build: ./substation_service
    environment:
      - SUSTATION_ID=1
    ports:
      - "8001:8000"
  
  substation2:
    build: ./substation_service
    environment:
      - SUSTATION_ID=2
    ports:
      - "8002:8000"
  
  substation3:
    build: ./substation_service
    environment:
      - SUSTATION_ID=3
    ports:
      - "8003:8000"
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus